# Site settings
title: tuschenskis blog
email: daniel.tuchscherer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! I'm Daniel. I work as a development engineer in the automotive domain. I'm passionate about automotive systems engineering, Modern C++, embedded systems and control engineering.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dtuchsch.github.io" # the base hostname & protocol for your site

github_username:  dtuchsch

# A profile picture for the index page
avatar: https://avatars3.githubusercontent.com/u/3890882?v=3&s=460

# Build settings
markdown: kramdown
highlighter: rouge
mathjax: true
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
theme: jekyll-theme-cayman

paginate: 5

plugins:
  - jekyll-seo-tag
