site_name: dtuchsch memo
pages:
- Home: index.md
- Quadrocopter:
   - 'Getting Started PX4': 'quadrocopter/Getting-Started-with-PX4-Toolchain.md'
- Linux:
   - 'Realtime-Preempt Kernel on Raspberry PI': 'linux/RT-PREEMPT-on-Raspberry-PI.md'
theme: readthedocs
site_author: Daniel Tuchscherer
copyright: Daniel Tuchscherer
site_dir: build
google_analytics: ['UA-64110372-1', 'dtuchsch.github.io/']